package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"app/graph/model"
	"context"
	"crypto/rand"
	"encoding/json"
	"fmt"
	"math/big"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	randNumber, _ := rand.Int(rand.Reader, big.NewInt(100))
	todo := &model.Todo{
		Text: input.Text,
		ID:   fmt.Sprintf("T%d", randNumber),
		User: &model.User{ID: input.UserID, Name: "user " + input.UserID},
	}
	r.todos = append(r.todos, todo)
	return todo, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	obj, err := rdb.JSONGet(ctx, "foo2").Result()
	if err != nil {
		return nil, nil
	}
	resObj := r.todos
	json.Unmarshal([]byte(obj), &resObj)
	return resObj, nil
	// return r.todos, nil
}

// Albums is the resolver for the albums field.
func (r *queryResolver) Albums(ctx context.Context) ([]*model.Album, error) {
	obj, err := rdb.JSONGet(ctx, "albums_array").Result()
	if err != nil {
		return nil, nil
	}
	var resObj []*model.Album
	json.Unmarshal([]byte(obj), &resObj)
	return resObj, nil
}

// SearchAlbums is the resolver for the searchAlbums field.
func (r *queryResolver) SearchAlbums(ctx context.Context, id *string) (*model.Album, error) {
	obj, err := rdb.JSONGet(ctx, "albums_array", "["+*id+"]").Result()
	if err != nil {
		return nil, nil
	}
	resObj := model.Album{}
	json.Unmarshal([]byte(obj), &resObj)
	return &resObj, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
