name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Just checking
      run: free -h
    - name: Building and Running Next app
      run: | 
        cd next-app/
        npm i
        npm run build --if-present
        pm2 reload 0
    - name: Building and Running gin-service
      run: |
        cd web-service-gin/
        ls
        go build cmd/api/main.go
        ls
        mv main gin-service
        ls
        ./gin-service &
    - name: Building and Running ql-service
      run: |
        cd gqlgen-web-service/
        ls
        go build server.go
        ls
        mv server ql-service
        ls
        ./ql-service &
