name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Just checking
      run: free -h
    - name: Building and Running gin-service
      run: |
        cd web-service-gin/
        go build cmd/api/main.go
        mv main gin-service
        pidof gin-service && killall gin-service || echo "No Process Found" 
        RUNNER_TRACKING_ID="" && ./gin-service &
        echo $?
        pidof gin-service
    - name: Building and Running ql-service
      run: |
        cd gqlgen-web-service/
        go build server.go
        mv server ql-service
        pidof ql-service && killall ql-service || echo "No Process Found"
        RUNNER_TRACKING_ID="" && ./ql-service &
        echo $?
        pidof ql-service
    - name: Building and Running custom-service
      run: |
        cd web-service-custom/
        go build main.go
        mv main custom-service
        pidof custom-service && killall custom-service || echo "No Process Found"
        RUNNER_TRACKING_ID="" && ./custom-service &
        echo $?
        pidof custom-service
    - name: Building and Running Next app
      run: | 
        cd next-app/
        npm i
        npm run build --if-present
        pm2 reload 0
