name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Just checking
      run: free -h
    - name: Building and Running Next app
      run: | 
        cd next-app/
        npm i
        npm run build --if-present
        pm2 reload 0
    - name: Building gin-service
      run: |
        cd web-service-gin/
        go build cmd/api/main.go
        mv main gin-service
    - name: Running gin-service
      run: ./gin-service &
    - name: Running ql-service
      run: |
        cd gqlgen-web-service/
        go build server.go
        mv server ql-service
    - name: Running ql-service
      run: ./ql-service &
